version: '3.1'
name: api-lotantsia-production

services:
  mongodb:
    image: mongo
    restart: on-failure:5 # On error, try to restart for a maximum of 5 times
    ports:
      - 27031:27017
    environment:
      MONGO_INITDB_DATABASE: api
    volumes:
      - dbvolumelotantsiaproduction:/data/db

  api:
    build:
      context: ../.
      dockerfile: packages/api/Dockerfile
    env_file:
      - ./../packages/api/.env.production.local
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/my-google-secret
    ports:
      - 8000:8000 # External:What Is Set In Main.ts
      - 3004:3004 # Socket
    secrets:
      - my-google-secret

  pwa:
    build:
      context: ../.
      dockerfile: packages/pwa/Dockerfile
    ports:
      - 8081:80
    env_file:
      - ./../packages/pwa/.env.production.local

volumes:
  dbvolumelotantsiaproduction:

secrets:
  my-google-secret:
    file: 'C:\School\MCT_2023\FullStack\Lotte-Antje-Alessia\packages\api\credentials.json'
